#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

#if [ ! -f $OPENSHIFT_DATA_DIR/db.sqlite3 ]
#then
#    echo "Copying $OPENSHIFT_REPO_DIR/wsgi/openshift/db.sqlite3 to $OPENSHIFT_DATA_DIR"
#    cp "$OPENSHIFT_REPO_DIR"wsgi/openshift/db.sqlite3 $OPENSHIFT_DATA_DIR
#    python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
#else
#    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput'"
#    python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py syncdb --noinput
#    python "$OPENSHIFT_REPO_DIR"wsgi/openshift/populate_db.py
#fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py syncdb --noinput

#echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py migrate --noinput'"
#python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py migrate --noinput

# First-time deploy for south, only run this the first time
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py schemamigration --initial'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py schemamigration --initial
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py migrate --fake'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py migrate --fake
# End of first-time deploy

echo "Executing populate script"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/populate_db.py

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/openshift/manage.py collectstatic --noinput
