# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0021_shoeorder_customer_ordered_date'),
        ('clients', '0043_auto_20161109_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('t', 'Text'), ('e', 'Email'), ('c', 'Call')], max_length=1)),
                ('follow_up_result', models.CharField(blank=True, choices=[('n', 'No answer'), ('v', 'Voicemail')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Claim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('t', 'Text'), ('e', 'Email'), ('c', 'Call')], max_length=1)),
                ('follow_up_result', models.CharField(blank=True, choices=[('n', 'No answer'), ('v', 'Voicemail')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.CoverageOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
