# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-10 20:46
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call')], default='r', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call')], default='r', max_length=1),
        ),
    ]
