# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-10 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_auto_20161110_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimreminder',
            old_name='follow_up_result',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='orderreminder',
            old_name='follow_up_result',
            new_name='result',
        ),
    ]
