# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_auto_20161110_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderReminder',
            new_name='OrderArrivedReminder',
        ),
        migrations.RenameModel(
            old_name='ClaimReminder',
            new_name='UnpaidClaimReminder',
        ),
    ]
