# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_auto_20161115_0202'),
        ('reminders', '0007_auto_20161116_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimOrderReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Claim')),
            ],
            bases=(models.Model, utils.model_utils.FieldList),
        ),
    ]
