# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_claimorderreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArrivedMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnpaidClaimMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderarrivedreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call'), ('o', 'Completed')], default='r', max_length=9),
        ),
        migrations.AlterField(
            model_name='unpaidclaimreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call'), ('o', 'Completed')], default='r', max_length=9),
        ),
        migrations.AddField(
            model_name='unpaidclaimmessagelog',
            name='unpaid_claim_reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.UnpaidClaimReminder'),
        ),
        migrations.AddField(
            model_name='orderarrivedmessagelog',
            name='order_arrived_reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.OrderArrivedReminder'),
        ),
    ]
