# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_auto_20170203_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderarrivedmessagelog',
            name='msg_type',
            field=models.CharField(choices=[('t', 'Text'), ('e', 'Email')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unpaidclaimmessagelog',
            name='msg_type',
            field=models.CharField(choices=[('t', 'Text'), ('e', 'Email')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
