# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0010_auto_20170203_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderarrivedmessagelog',
            name='order_arrived_reminder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.OrderArrivedReminder'),
        ),
        migrations.AlterField(
            model_name='unpaidclaimmessagelog',
            name='unpaid_claim_reminder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.UnpaidClaimReminder'),
        ),
    ]
