# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-03 20:10
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0012_auto_20170207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderarrivedreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call'), ('o', 'Completed'), ('d', 'Deleted')], default='r', max_length=11),
        ),
        migrations.AlterField(
            model_name='unpaidclaimreminder',
            name='follow_up',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call'), ('o', 'Completed'), ('d', 'Deleted')], default='r', max_length=11),
        ),
    ]
