# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-16 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_auto_20190416_1533'),
        ('reminders', '0013_auto_20180303_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up', multiselectfield.db.fields.MultiSelectField(choices=[('r', 'Required'), ('t', 'Text'), ('e', 'Email'), ('c', 'Call'), ('o', 'Completed'), ('d', 'Deleted')], default='r', max_length=11)),
                ('result', models.CharField(blank=True, choices=[('n', 'No answer'), ('v', 'Voicemail')], max_length=1)),
                ('created', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('coverages', models.ManyToManyField(to='clients.Coverage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.model_utils.FieldList),
        ),
    ]
