# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-04-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0014_benefitsreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('t', 'Text'), ('e', 'Email'), ('c', 'Call')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('benefits_reminder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminders.BenefitsReminder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
