# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_auto_20160428_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomechanical',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arch_height_non_weight_high_left', models.BooleanField(default=False)),
                ('arch_height_non_weight_high_right', models.BooleanField(default=False)),
                ('arch_height_non_weight_medium_left', models.BooleanField(default=False)),
                ('arch_height_non_weight_medium_right', models.BooleanField(default=False)),
                ('arch_height_non_weight_low_left', models.BooleanField(default=False)),
                ('arch_height_non_weight_low_right', models.BooleanField(default=False)),
                ('arch_height_weight_high_left', models.BooleanField(default=False)),
                ('arch_height_weight_high_right', models.BooleanField(default=False)),
                ('arch_height_weight_medium_left', models.BooleanField(default=False)),
                ('arch_height_weight_medium_right', models.BooleanField(default=False)),
                ('arch_height_weight_low_left', models.BooleanField(default=False)),
                ('arch_height_weight_low_right', models.BooleanField(default=False)),
                ('gait_toe_in', models.BooleanField(default=False)),
                ('gait_straight', models.BooleanField(default=False)),
                ('gait_toe_out', models.BooleanField(default=False)),
                ('supination', models.BooleanField(default=False)),
                ('supination_mild_left', models.BooleanField(default=False)),
                ('supination_mild_right', models.BooleanField(default=False)),
                ('supination_moderate_left', models.BooleanField(default=False)),
                ('supination_moderate_right', models.BooleanField(default=False)),
                ('supination_severe_left', models.BooleanField(default=False)),
                ('supination_severe_right', models.BooleanField(default=False)),
                ('pronation', models.BooleanField(default=False)),
                ('pronation_mild_left', models.BooleanField(default=False)),
                ('pronation_mild_right', models.BooleanField(default=False)),
                ('pronation_moderate_left', models.BooleanField(default=False)),
                ('pronation_moderate_right', models.BooleanField(default=False)),
                ('pronation_severe_left', models.BooleanField(default=False)),
                ('pronation_severe_right', models.BooleanField(default=False)),
                ('ankle_dorsi_flexion_adequate_left', models.BooleanField(default=False)),
                ('ankle_dorsi_flexion_adequate_right', models.BooleanField(default=False)),
                ('ankle_dorsi_flexion_limited_left', models.BooleanField(default=False)),
                ('ankle_dorsi_flexion_limited_right', models.BooleanField(default=False)),
                ('general_foot_motion_restricted_left', models.BooleanField(default=False)),
                ('general_foot_motion_restricted_right', models.BooleanField(default=False)),
                ('general_foot_motion_normal_left', models.BooleanField(default=False)),
                ('general_foot_motion_normal_right', models.BooleanField(default=False)),
                ('general_foot_motion_hyper_mobile_left', models.BooleanField(default=False)),
                ('general_foot_motion_hyper_mobile_right', models.BooleanField(default=False)),
                ('forefoot_varus', models.BooleanField(default=False)),
                ('forefoot_varus_mild_left', models.BooleanField(default=False)),
                ('forefoot_varus_mild_right', models.BooleanField(default=False)),
                ('forefoot_varus_moderate_left', models.BooleanField(default=False)),
                ('forefoot_varus_moderate_right', models.BooleanField(default=False)),
                ('forefoot_varus_severe_left', models.BooleanField(default=False)),
                ('forefoot_varus_severe_right', models.BooleanField(default=False)),
                ('forefoot_valgus', models.BooleanField(default=False)),
                ('forefoot_valgus_mild_left', models.BooleanField(default=False)),
                ('forefoot_valgus_mild_right', models.BooleanField(default=False)),
                ('forefoot_valgus_moderate_left', models.BooleanField(default=False)),
                ('forefoot_valgus_moderate_right', models.BooleanField(default=False)),
                ('forefoot_valgus_severe_left', models.BooleanField(default=False)),
                ('forefoot_valgus_severe_right', models.BooleanField(default=False)),
                ('subtalar_joint_hyper_mobile', models.BooleanField(default=False)),
                ('subtalar_joint_limited_rom', models.BooleanField(default=False)),
                ('ankle_joint_hyper_mobile', models.BooleanField(default=False)),
                ('ankle_joint_limited_rom', models.BooleanField(default=False)),
                ('first_mpj_hyper_mobile', models.BooleanField(default=False)),
                ('first_mpj_limited_rom', models.BooleanField(default=False)),
                ('casual_functional_2mm', models.BooleanField(default=False)),
                ('casual_functional_3mm', models.BooleanField(default=False)),
                ('casual_functional_35mm', models.BooleanField(default=False, verbose_name='Casual functional 3.5mm')),
                ('casual_functional_34', models.BooleanField(default=False, verbose_name='Casual functional 3/4')),
                ('casual_functional_sulcus', models.BooleanField(default=False)),
                ('casual_functional_full_length', models.BooleanField(default=False)),
                ('casual_kids_2mm', models.BooleanField(default=False)),
                ('casual_kids_3mm', models.BooleanField(default=False)),
                ('casual_kids_35mm', models.BooleanField(default=False, verbose_name='Casual kids 3.5mm')),
                ('casual_kids_34', models.BooleanField(default=False, verbose_name='Casual kids 3/4')),
                ('casual_kids_full_length', models.BooleanField(default=False)),
                ('casual_accommodative_2mm', models.BooleanField(default=False)),
                ('casual_accommodative_sulcus', models.BooleanField(default=False)),
                ('casual_accommodative_full_length', models.BooleanField(default=False)),
                ('dress_dress_2mm', models.BooleanField(default=False)),
                ('dress_dress_3mm', models.BooleanField(default=False)),
                ('dress_dress_35mm', models.BooleanField(default=False, verbose_name='Dress dress 3.5mm')),
                ('dress_dress_34', models.BooleanField(default=False, verbose_name='Dress dress 3/4')),
                ('dress_dress_sulcus', models.BooleanField(default=False)),
                ('dress_dress_full_length', models.BooleanField(default=False)),
                ('dress_fashion_2mm', models.BooleanField(default=False)),
                ('dress_fashion_3mm', models.BooleanField(default=False)),
                ('dress_fashion_35mm', models.BooleanField(default=False, verbose_name='Dress fashion 3.5mm')),
                ('dress_fashion_full_length', models.BooleanField(default=False)),
                ('sport_sport_2mm', models.BooleanField(default=False)),
                ('sport_sport_3mm', models.BooleanField(default=False)),
                ('sport_sport_35mm', models.BooleanField(default=False, verbose_name='Sport sport 3.5mm')),
                ('sport_sport_34', models.BooleanField(default=False, verbose_name='Sport sport 3/4')),
                ('sport_sport_sulcus', models.BooleanField(default=False)),
                ('sport_sport_full_length', models.BooleanField(default=False)),
                ('sport_run_2mm', models.BooleanField(default=False)),
                ('sport_run_3mm', models.BooleanField(default=False)),
                ('sport_run_35mm', models.BooleanField(default=False, verbose_name='Sport run 3.5mm')),
                ('sport_run_sulcus', models.BooleanField(default=False)),
                ('sport_run_full_length', models.BooleanField(default=False)),
                ('sport_eagle_2mm', models.BooleanField(default=False)),
                ('sport_eagle_3mm', models.BooleanField(default=False)),
                ('sport_eagle_35mm', models.BooleanField(default=False, verbose_name='Sport eagle 3.5mm')),
                ('sport_eagle_34', models.BooleanField(default=False, verbose_name='Sport eagle 3/4')),
                ('sport_eagle_sulcus', models.BooleanField(default=False)),
                ('sport_eagle_full_length', models.BooleanField(default=False)),
                ('sport_ski_2mm', models.BooleanField(default=False)),
                ('sport_ski_3mm', models.BooleanField(default=False)),
                ('sport_ski_35mm', models.BooleanField(default=False, verbose_name='Sport ski 3.5mm')),
                ('sport_ski_sulcus', models.BooleanField(default=False)),
                ('sport_ski_full_length', models.BooleanField(default=False)),
                ('sport_skate_2mm', models.BooleanField(default=False)),
                ('sport_skate_3mm', models.BooleanField(default=False)),
                ('sport_skate_35mm', models.BooleanField(default=False, verbose_name='Sport skate 3.5mm')),
                ('sport_skate_sulcus', models.BooleanField(default=False)),
                ('sport_skate_full_length', models.BooleanField(default=False)),
                ('sport_court_2mm', models.BooleanField(default=False)),
                ('sport_court_3mm', models.BooleanField(default=False)),
                ('sport_court_35mm', models.BooleanField(default=False, verbose_name='Sport court 3.5mm')),
                ('sport_court_sulcus', models.BooleanField(default=False)),
                ('sport_court_full_length', models.BooleanField(default=False)),
                ('sport_soccer_2mm', models.BooleanField(default=False)),
                ('sport_soccer_3mm', models.BooleanField(default=False)),
                ('sport_soccer_35mm', models.BooleanField(default=False, verbose_name='Sport soccer 3.5mm')),
                ('sport_soccer_sulcus', models.BooleanField(default=False)),
                ('sport_soccer_full_length', models.BooleanField(default=False)),
                ('sport_safety_2mm', models.BooleanField(default=False)),
                ('sport_safety_3mm', models.BooleanField(default=False)),
                ('sport_safety_35mm', models.BooleanField(default=False, verbose_name='Sport safety 3.5mm')),
                ('sport_safety_sulcus', models.BooleanField(default=False)),
                ('sport_safety_full_length', models.BooleanField(default=False)),
                ('leather_sulcus', models.BooleanField(default=False)),
                ('leather_full', models.BooleanField(default=False)),
                ('leather_heel_spur_pad', models.BooleanField(default=False)),
                ('leather_heel_lift', models.BooleanField(default=False)),
                ('leather_heel_lift_l', models.CharField(blank=True, max_length=5)),
                ('leather_heel_lift_r', models.CharField(blank=True, max_length=5)),
                ('ucbl_1mm', models.BooleanField(default=False)),
                ('ucbl_2mm', models.BooleanField(default=False)),
                ('gait_plate_2mm', models.BooleanField(default=False)),
                ('gait_plate_3mm', models.BooleanField(default=False)),
                ('gait_plate_35mm', models.BooleanField(default=False, verbose_name='Gait plate 3.5mm')),
                ('gait_plate_induce_toe_in', models.BooleanField(default=False)),
                ('gait_plate_induce_toe_out', models.BooleanField(default=False)),
                ('diabetic_34', models.BooleanField(default=False, verbose_name='Diabetic 3/4')),
                ('diabetic_sulcus', models.BooleanField(default=False)),
                ('diabetic_full_length', models.BooleanField(default=False)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('shoe_size', models.CharField(blank=True, max_length=5)),
                ('shoe_type', models.CharField(blank=True, max_length=16)),
                ('main_activities', models.CharField(blank=True, max_length=32)),
                ('fabricate', models.BooleanField(default=False)),
                ('chief_complaints_special_instructions', models.TextField(blank=True)),
                ('full_heel_cushion', models.BooleanField(default=False)),
                ('neuroma_pad', models.BooleanField(default=False)),
                ('neuroma_pad_l_1', models.CharField(blank=True, max_length=5)),
                ('neuroma_pad_l_2', models.CharField(blank=True, max_length=5)),
                ('neuroma_pad_r_1', models.CharField(blank=True, max_length=5)),
                ('neuroma_pad_r_2', models.CharField(blank=True, max_length=5)),
                ('metatarsal_pad', models.BooleanField(default=False)),
                ('metatarsal_pad_low_profile', models.BooleanField(default=False)),
                ('metatarsal_pad_distal_placement', models.BooleanField(default=False)),
                ('forefoot_pad_to_sulcus', models.BooleanField(default=False)),
                ('forefoot_pad_to_sulcus_l', models.CharField(blank=True, max_length=5)),
                ('forefoot_pad_to_sulcus_r', models.CharField(blank=True, max_length=5)),
                ('sub_metatarsal_accommodation', models.BooleanField(default=False)),
                ('sub_metatarsal_accommodation_l', models.CharField(blank=True, max_length=5)),
                ('sub_metatarsal_accommodation_r', models.CharField(blank=True, max_length=5)),
                ('heel_spur_pad', models.BooleanField(default=False)),
                ('heel_spur_pad_l', models.CharField(blank=True, max_length=5)),
                ('heel_spur_pad_r', models.CharField(blank=True, max_length=5)),
                ('mortons_extension', models.BooleanField(default=False)),
                ('mortons_extension_l', models.CharField(blank=True, max_length=5)),
                ('mortons_extension_r', models.CharField(blank=True, max_length=5)),
                ('reinforced_arch', models.BooleanField(default=False, verbose_name='Reinforced arch (greater than 280lbs)')),
                ('rearfoot_extrinsic_post', models.BooleanField(default=False)),
                ('rearfoot_extrinsic_post_l', models.CharField(blank=True, max_length=5)),
                ('rearfoot_extrinsic_post_r', models.CharField(blank=True, max_length=5)),
                ('medial_skive', models.BooleanField(default=False)),
                ('medial_skive_l', models.CharField(blank=True, max_length=5)),
                ('medial_skive_r', models.CharField(blank=True, max_length=5)),
                ('lateral_skive', models.BooleanField(default=False)),
                ('lateral_skive_l', models.CharField(blank=True, max_length=5)),
                ('lateral_skive_r', models.CharField(blank=True, max_length=5)),
                ('hole_in_heel', models.BooleanField(default=False)),
                ('hole_in_heel_l', models.CharField(blank=True, max_length=5)),
                ('hole_in_heel_r', models.CharField(blank=True, max_length=5)),
                ('hole_in_heel_with_foam_disk', models.BooleanField(default=False)),
                ('reverse_mortons_extension', models.BooleanField(default=False)),
                ('reverse_mortons_extension_l', models.CharField(blank=True, max_length=5)),
                ('reverse_mortons_extension_r', models.CharField(blank=True, max_length=5)),
                ('extrinsic_forefoot_post_34_length', models.BooleanField(default=False, verbose_name='Extrinsic forefoot post (3/4 length)')),
                ('extrinsic_forefoot_post_34_length_l', models.CharField(verbose_name='Extrinsic forefoot post (3/4 length) L', blank=True, max_length=5)),
                ('extrinsic_forefoot_post_34_length_r', models.CharField(verbose_name='Extrinsic forefoot post (3/4 length) R', blank=True, max_length=5)),
                ('heel_lift', models.BooleanField(default=False)),
                ('heel_lift_l', models.CharField(blank=True, max_length=5)),
                ('heel_lift_r', models.CharField(blank=True, max_length=5)),
                ('deep_heel_cups', models.BooleanField(default=False)),
                ('deep_heel_cups_l', models.CharField(blank=True, max_length=5)),
                ('deep_heel_cups_r', models.CharField(blank=True, max_length=5)),
                ('first_metatarsal_cut_out', models.BooleanField(default=False)),
                ('first_metatarsal_cut_out_l', models.CharField(blank=True, max_length=5)),
                ('first_metatarsal_cut_out_r', models.CharField(blank=True, max_length=5)),
                ('extrinsic_forefoot_post_sulcus_length', models.BooleanField(default=False, verbose_name='Extrinsic forefoot post (sulcus length)')),
                ('extrinsic_forefoot_post_sulcus_length_l', models.CharField(verbose_name='Extrinsic forefoot post (sulcus length) L', blank=True, max_length=5)),
                ('extrinsic_forefoot_post_sulcus_length_r', models.CharField(verbose_name='Extrinsic forefoot post (sulcus length) R', blank=True, max_length=5)),
                ('vinyl_sandwich_bilateral', models.BooleanField(default=False, verbose_name='Vinyl sandwich (bilateral)')),
                ('medial_flange', models.BooleanField(default=False)),
                ('medial_flange_l', models.CharField(blank=True, max_length=5)),
                ('medial_flange_r', models.CharField(blank=True, max_length=5)),
                ('lateral_flange', models.BooleanField(default=False)),
                ('lateral_flange_l', models.CharField(blank=True, max_length=5)),
                ('lateral_flange_r', models.CharField(blank=True, max_length=5)),
                ('extra_foam_padding_topcover_18', models.BooleanField(default=False, verbose_name='Extra foam padding under topcover 1/8"')),
                ('extra_foam_padding_topcover_116', models.BooleanField(default=False, verbose_name='Extra foam padding under topcover 1/16"')),
                ('suede_leather_topcover', models.BooleanField(default=False, verbose_name='Suede leather topcover on orthotic ($10 additional charge)')),
                ('other_topcover', models.CharField(verbose_name='Other topcover (please specify)', blank=True, max_length=16)),
                ('claim', models.OneToOneField(to='clients.Claim')),
            ],
            bases=(models.Model, utils.model_utils.FieldList),
        ),
    ]
