# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-03 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_auto_20160527_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependent',
            old_name='client',
            new_name='primary',
        ),
    ]
