# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_auto_20161109_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('view_statistics', 'Can see statistics'),)},
        ),
        migrations.AlterField(
            model_name='claimcoverage',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Paid', (('cas', 'Cash'), ('che', 'Cheque'), ('vis', 'VISA'), ('mas', 'MasterCard'), ('deb', 'Interac Debit'), ('etr', 'e-Transfer'))), ('Not paid', (('del', 'Delinquent'), ('noc', 'No coverage')))], max_length=3),
        ),
    ]
