# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_auto_20161115_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='information',
            field=models.CharField(choices=[('moll', 'MA Orthotics Laboratory Ltd\n11975 W Sample Rd\nCoral Springs, FL  331000\nUSA\n\nPhone: (754) 206-6110\nFax: (754) 206-6109\n\nLaboratory Supervisor: M. Asam C.Ped.'), ('ooli', 'OOLab Inc.\n42 Niagara St\nHamilton, ON  L8L 6A2\nCanada\nToll Free: 1-888-873-3316\nPhone: (905) 521-1230\nFax: (905) 521-1210\nEmail: info@oolab.com\nLaboratory Supervisor: A. Boyle'), ('aror', 'Ares Orthotics\n107 Ave SE\nCalgary, AB  T2Z 3R7\nCanada\n\nPhone: (403) 398-5629\nFax: (403) 398-5635\nEmail: acct@aresorthotics.com\nLaboratory Supervisor: B. Domosky'), ('iorl', 'International Orthotics Lab\n6777 Fairmount Drive SE\nCalgary, AB  T2H 0X6\nCanada\n\nPhone: (403) 236-8540\nFax: (403) 236-8539\nEmail: info@orthotic.caLaboratory Supervisor: Lou-Anne Knopp'), ('paoi', 'The Perfect Arch Orthotics Inc.\n10540 - 169 St.\nEdmonton, AB  T5P 3X6\nCanada\n\nPhone: (587) 400-4588\nFax: (587) 400-4566\nEmail: danny@perfectarch\nLaboratory Supervisor: Danny Mu')], max_length=8, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='proofofmanufacturing',
            name='laboratory',
            field=models.CharField(choices=[('moll', 'MA Orthotics Laboratory Ltd\n11975 W Sample Rd\nCoral Springs, FL  331000\nUSA\n\nPhone: (754) 206-6110\nFax: (754) 206-6109\n\nLaboratory Supervisor: M. Asam C.Ped.'), ('ooli', 'OOLab Inc.\n42 Niagara St\nHamilton, ON  L8L 6A2\nCanada\nToll Free: 1-888-873-3316\nPhone: (905) 521-1230\nFax: (905) 521-1210\nEmail: info@oolab.com\nLaboratory Supervisor: A. Boyle'), ('aror', 'Ares Orthotics\n107 Ave SE\nCalgary, AB  T2Z 3R7\nCanada\n\nPhone: (403) 398-5629\nFax: (403) 398-5635\nEmail: acct@aresorthotics.com\nLaboratory Supervisor: B. Domosky'), ('iorl', 'International Orthotics Lab\n6777 Fairmount Drive SE\nCalgary, AB  T2H 0X6\nCanada\n\nPhone: (403) 236-8540\nFax: (403) 236-8539\nEmail: info@orthotic.caLaboratory Supervisor: Lou-Anne Knopp'), ('paoi', 'The Perfect Arch Orthotics Inc.\n10540 - 169 St.\nEdmonton, AB  T5P 3X6\nCanada\n\nPhone: (587) 400-4588\nFax: (587) 400-4566\nEmail: danny@perfectarch\nLaboratory Supervisor: Danny Mu')], max_length=4),
        ),
    ]
