# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-11-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_auto_20170614_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='insurance2',
            field=models.ManyToManyField(to='clients.Insurance'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldclaim_set', to='clients.Insurance', verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='information',
            field=models.CharField(choices=[('moll', 'MA Orthotics Laboratory Ltd\n11975 W Sample Rd\nCoral Springs, FL  331000\nUSA\n\nPhone: (754) 206-6110\nFax: (754) 206-6109\n\nLaboratory Supervisor: M. Asam C.Ped.'), ('ooli', 'OOLab Inc.\n42 Niagara St\nHamilton, ON  L8L 6A2\nCanada\nToll Free: 1-888-873-3316\nPhone: (905) 521-1230\nFax: (905) 521-1210\nEmail: info@oolab.com\nLaboratory Supervisor: A. Boyle'), ('aror', 'Ares Orthotics\n107 Ave SE\nCalgary, AB  T2Z 3R7\nCanada\n\nPhone: (403) 398-5629\nFax: (403) 398-5635\nEmail: acct@aresorthotics.com\nLaboratory Supervisor: B. Domosky'), ('iorl', 'International Orthotics Lab\n6777 Fairmount Drive SE\nCalgary, AB  T2H 0X6\nCanada\n\nPhone: (403) 236-8540\nFax: (403) 236-8539\nEmail: info@orthotic.ca\nLaboratory Supervisor: Lou-Anne Knopp'), ('paoi', 'The Perfect Arch Orthotics Inc.\n10540 - 169 St.\nEdmonton, AB  T5P 3X6\nCanada\n\nPhone: (587) 400-4588\nFax: (587) 400-4566\nEmail: danny@perfectarch\nLaboratory Supervisor: Danny Mu'), ('porl', 'Paragon Orthotic Laboratory\n1650 Cedar Hill Cross Road\nVictoria, BC  V8P 2P6\nCanada\n\nPhone: (250) 721-1112\nFax: (250) 721-1160\nEmail: info@paragonorthotic.com\nLaboratory Supervisor: Eve Podolsky')], max_length=8, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='proofofmanufacturing',
            name='laboratory',
            field=models.CharField(choices=[('moll', 'MA Orthotics Laboratory Ltd\n11975 W Sample Rd\nCoral Springs, FL  331000\nUSA\n\nPhone: (754) 206-6110\nFax: (754) 206-6109\n\nLaboratory Supervisor: M. Asam C.Ped.'), ('ooli', 'OOLab Inc.\n42 Niagara St\nHamilton, ON  L8L 6A2\nCanada\nToll Free: 1-888-873-3316\nPhone: (905) 521-1230\nFax: (905) 521-1210\nEmail: info@oolab.com\nLaboratory Supervisor: A. Boyle'), ('aror', 'Ares Orthotics\n107 Ave SE\nCalgary, AB  T2Z 3R7\nCanada\n\nPhone: (403) 398-5629\nFax: (403) 398-5635\nEmail: acct@aresorthotics.com\nLaboratory Supervisor: B. Domosky'), ('iorl', 'International Orthotics Lab\n6777 Fairmount Drive SE\nCalgary, AB  T2H 0X6\nCanada\n\nPhone: (403) 236-8540\nFax: (403) 236-8539\nEmail: info@orthotic.ca\nLaboratory Supervisor: Lou-Anne Knopp'), ('paoi', 'The Perfect Arch Orthotics Inc.\n10540 - 169 St.\nEdmonton, AB  T5P 3X6\nCanada\n\nPhone: (587) 400-4588\nFax: (587) 400-4566\nEmail: danny@perfectarch\nLaboratory Supervisor: Danny Mu'), ('porl', 'Paragon Orthotic Laboratory\n1650 Cedar Hill Cross Road\nVictoria, BC  V8P 2P6\nCanada\n\nPhone: (250) 721-1112\nFax: (250) 721-1160\nEmail: info@paragonorthotic.com\nLaboratory Supervisor: Eve Podolsky')], max_length=4),
        ),
    ]
