# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-11-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_auto_20181103_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='insurance2',
            new_name='insurances',
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='oldclaim_set', to='clients.Insurance', verbose_name='Insurance'),
        ),
    ]
