# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-01-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_remove_claim_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
