# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-01-27 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_update_invoice_number_20190127_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
