# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-10-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_biomechanicalgait2'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomechanicalgait2',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='biomechanicalgait2',
            name='patient_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='biomechanicalgait2',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='biomechanicalgait2',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='biomechanicalgait2',
            name='provider',
            field=models.CharField(max_length=128, verbose_name='Insurance'),
        ),
    ]
