# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-01-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_auto_20191022_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='coverage_type',
            field=models.CharField(blank=True, choices=[('o', 'Orthotics'), ('cs', 'Compression Stockings'), ('os', 'Orthopedic Shoes'), ('bs', 'Back Support'), ('kb', 'Knee Brace'), ('wb', 'Wrist Brace'), ('ab', 'Ankle Brace'), ('tm', 'TENS Machine'), ('sb', 'Shoulder Brace'), ('nb', 'Neck Brace'), ('om', 'Other Medical Equipment')], max_length=4, verbose_name='Coverage Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='coverage_type',
            field=models.CharField(choices=[('o', 'Orthotics'), ('cs', 'Compression Stockings'), ('os', 'Orthopedic Shoes'), ('bs', 'Back Support'), ('kb', 'Knee Brace'), ('wb', 'Wrist Brace'), ('ab', 'Ankle Brace'), ('tm', 'TENS Machine'), ('sb', 'Shoulder Brace'), ('nb', 'Neck Brace'), ('om', 'Other Medical Equipment')], max_length=4, verbose_name='Coverage Type'),
        ),
    ]
