# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-01-28 00:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_invoice_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Retail'),
        ),
    ]
