# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-04-03 22:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_auto_20220210_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcoverage',
            name='expected_back',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Expected Back'),
        ),
    ]
