# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-09-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0064_auto_20240917_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.CharField(choices=[('pa', 'Perfect Arch'), ('pc', 'PC Medical'), ('bb', 'Brace and Body'), ('op', 'Orthotics Pros')], default='pa', max_length=2),
        ),
    ]
