# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_auto_20161115_0202'),
        ('inventory', '0021_shoeorder_customer_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageorder',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Claim'),
        ),
    ]
