# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_coverageorder_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeorder',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
