# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20170614_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageorder',
            name='customer_ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
