# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-23 21:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_coverageorder_customer_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageorder',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, verbose_name='Credit Value'),
        ),
    ]
