# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2019-01-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20180223_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeattributes',
            name='size',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13'), ('13.5', '13.5'), ('14', '14'), ('14.5', '14.5'), ('15', '15'), ('15.5', '15.5'), ('16', '16'), ('16.5', '16.5'), ('17', '17'), ('17.5', '17.5'), ('18', '18')], max_length=4, verbose_name='Size'),
        ),
    ]
