# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2022-01-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20190127_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('o', 'Orthotics'), ('cs', 'Compression Stockings'), ('os', 'Orthopedic Shoes'), ('bs', 'Back Support'), ('kb', 'Knee Brace'), ('wb', 'Wrist Brace'), ('ab', 'Ankle Brace'), ('tm', 'TENS Machine'), ('sb', 'Shoulder Brace'), ('nb', 'Neck Brace'), ('om', 'Other Medical Equipment'), ('s', 'Shoe'), ('a', 'Adjustment')], max_length=4, verbose_name='Order Type'),
        ),
    ]
